FROM python:3.12-slim-bookworm

# Copy all files in ./app
WORKDIR /app
COPY app/* /app

# Install the specified packages
RUN pip install -r requirements.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "python", "app.py" ]